
# Run the application from the cmd directory
run:
	go run ./cmd

# Build the binary into bin/api-gateway
build:
	go build -o bin/api-gateway ./cmd

# Start the built binary
start:
	./bin/api-gateway

# Clean build artifacts
clean:
	rm -rf bin/
